import './globals.scss';
import Header from '@/components/Header/Header';
export const metadata = {
  title: 'TrackOnWeb',
  description: 'Generated by Next.js',
};
import { store } from '@/redux_toolkit/redux_store/store';
import { Providers } from '@/redux_toolkit/redux_store/provider';

// window.addEventListener('visibilitychange', () => {
//   document.title = 'Come back';
// });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <header>
            <Header />
          </header>
          {children}
        </body>
      </html>
    </Providers>
  );
}
