import './globals.scss';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import Login from '@/components/Modals/Login';
export const metadata = {
  title: 'TrackOnWeb',
  description: 'Generated by Next.js',
};
import { Providers } from '@/redux_toolkit/redux_store/provider';

// window.addEventListener('visibilitychange', () => {
//   document.title = 'Come back';
// });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <header>
            <Header />
          </header>
          <main>
            {children}
            <Login />
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </Providers>
  );
}
